Comercializadora/Comercializadora/Models/DetalleFactura.cs
namespace Comercializadora.Models
{
    public class DetalleFactura
    {
        public int ProductoId { get; set; }

        public int FacturaId { get; set; }

        public string NombreProducto { get; set; }

        public int Cantidad { get; set; }

        public decimal PrecioUnitario { get; set; }

    }
}

Comercializadora/Comercializadora/Models/ErrorViewModel.cs
namespace Comercializadora.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Comercializadora/Comercializadora/Models/Factura.cs
using System.ComponentModel.DataAnnotations;

namespace Comercializadora.Models
{
    public class Factura
    {
        public int Id { get; set; }

        [Required]
        public string NombreCliente { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }  
    }
}

Comercializadora/Comercializadora/Models/Producto.cs
namespace Comercializadora.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }

    }
}

Comercializadora/Comercializadora/Controllers/DetalleFacturaController.cs
using Comercializadora.Models;
using Comercializadora.Service;
using Microsoft.AspNetCore.Mvc;

namespace Comercializadora.Controllers
{
    public class DetalleFacturaController : Controller
    {

        public readonly IDetalleFacturaService _detalleFacturaService;
        public readonly IProductoService _productoService;

        public DetalleFacturaController(IDetalleFacturaService detalleFacturaService, IProductoService productoService)
        {
            _detalleFacturaService = detalleFacturaService;
            _productoService = productoService;
        }

        [HttpGet]
        public IActionResult Crear(int id)
        {
            ViewBag.Productos = _productoService.ObtenerProductos();
            var detalle = new DetalleFactura
            {
                FacturaId = id
            };  
            return View(detalle);
        }

        [HttpPost]
        public IActionResult Crear(DetalleFactura detalle)
        {
            ModelState.Remove("Factura");
            ModelState.Remove("NombreProducto");
            ModelState.Remove("PrecioUnitario");

            if (ModelState.IsValid)
            {
                _detalleFacturaService.AgregarDetalle(detalle);
                return RedirectToAction("Crear", new { id = detalle.FacturaId });
            }
            ViewBag.Productos = _productoService.ObtenerProductos();
            return View(detalle);
        }



    }
}

Comercializadora/Comercializadora/Controllers/FacturaController.cs
using AspNetCoreGeneratedDocument;
using Comercializadora.Models;
using Comercializadora.Service;
using Microsoft.AspNetCore.Mvc;

namespace Comercializadora.Controllers
{
    public class FacturaController : Controller
    {

        public readonly IFacturaService _facturaService;
        public readonly IDetalleFacturaService _detalleFacturaService;

        public FacturaController(IFacturaService facturaService, IDetalleFacturaService detalleFacturaService)
        {
            _facturaService = facturaService;
            _detalleFacturaService= detalleFacturaService;
        }
        public IActionResult Index()
        {
            var facturas = _facturaService.ObtenerFacturas();
            return View(facturas);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Factura factura)
        {
            _facturaService.AgregarFactura(factura);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var factura = _facturaService.ObtenerFacturas().FirstOrDefault(f => f.Id == id);
            var detalle = _detalleFacturaService.ObtenerDetallesPorFactura(id);

            ViewBag.Detalles= detalle;
            return View(factura);




        }
        public FileResult DescargarTxt(int id)
        {
            var factura = _facturaService.ObtenerFacturas().FirstOrDefault(f => f.Id == id);
            var detalles = _detalleFacturaService.ObtenerDetallesPorFactura(id);

            string contenido = $"Cliente: {factura.NombreCliente}\n" +
                               $"Fecha: {factura.Fecha:dd/MM/yyyy}\n\n" +
                               "Productos:\n";

            foreach (var detalle in detalles)
            {
                contenido += $"{detalle.NombreProducto} - Cantidad: {detalle.Cantidad} - Precio: {detalle.PrecioUnitario}\n";
            }

            contenido += $"\nSubtotal: {factura.Subtotal}\n" +
                         $"Impuesto: {factura.Impuesto}\n" +
                         $"Total: {factura.Total}";

            byte[] archivoBytes = System.Text.Encoding.UTF8.GetBytes(contenido);
            string contentType = "text/plain";
            string fileName = $"Factura_{factura.Id}.txt";

            return File(archivoBytes, contentType, fileName);
        }

    }
}

Comercializadora/Comercializadora/Controllers/HomeController.cs
using System.Diagnostics;
using Comercializadora.Models;
using Microsoft.AspNetCore.Mvc;

namespace Comercializadora.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Comercializadora/Comercializadora/Controllers/ProductoController.cs
using Comercializadora.Models;
using Comercializadora.Service;
using Microsoft.AspNetCore.Mvc;
namespace Comercializadora.Controllers
{


    public class ProductoController : Controller
    {

        public readonly IProductoService _productoService;

        public ProductoController(IProductoService productoService)
        {
            _productoService = productoService;
        }
        public IActionResult Index()
        {
            var productos = _productoService.ObtenerProductos();
            return View(productos);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Crear(Producto producto)
        {
            _productoService.AgregarProducto(producto);
            return RedirectToAction("Index");
        }
    }
}

Comercializadora/Comercializadora/Views/DetalleFactura/Crear.cshtml
@model Comercializadora.Models.DetalleFactura

@{
    ViewData["Title"] = "Agregar Detalle";
}

<h2 class="mb-3">Agregar Producto a Factura </h2>

<form asp-action="Crear" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="FacturaId" class="form-label">Número de Factura</label>
        <input asp-for="FacturaId" class="form-control" type="number" readonly />
        <span asp-validation-for="FacturaId" class="text-danger"></span>
    </div>

    <div class="col-md-6">
        <label class="form-label">Producto</label>
        <select asp-for="ProductoId" class="form-select" required>
            <option value="">-- Seleccione un producto --</option>
            @foreach (var producto in ViewBag.Productos)
            {
                <option value="@producto.Id">@producto.Nombre (@producto.Precio)</option>
            }
        </select>
        <span asp-validation-for="ProductoId" class="text-danger"></span>
    </div>

    <div class="col-md-6">
        <label asp-for="Cantidad" class="form-label">Cantidad</label>
      
        <input asp-for="Cantidad" class="form-control" type="number" min="1" required />
        <span asp-validation-for="Cantidad" class="text-danger"></span>
    </div>

    <div class="col-12">
        <button type="submit" class="btn btn-primary">Guardar</button>
       
        <a asp-controller="Factura" asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

Comercializadora/Comercializadora/Views/Factura/Crear.cshtml
@model Comercializadora.Models.Factura

@{
    ViewData["Title"] = "Crear Factura";
}

<h2 class="mb-3">Crear Factura</h2>

<form asp-action="Crear"
      method="post"
      enctype="multipart/form-data"
      class="row g-3">

      

    <div class="col-md-6">
        <label asp-for="NombreCliente" class="form-label"></label>
        <input asp-for="NombreCliente" class="form-control" />
        <span asp-validation-for="NombreCliente" class="text-danger"></span>
    </div>

    <div class="col-md-6">
        <label asp-for="Fecha" class="form-label"></label>
        <input asp-for="Fecha" class="form-control" />
        <span asp-validation-for="Fecha" class="text-danger"></span>
    </div>


    <div class="col-12">
        <button type="submit" class="btn btn-primary">
            Guardar
        </button>
        <a asp-action="Index" class="btn btn-secondary">
            Cancelar
        </a>
    </div>
</form>

Comercializadora/Comercializadora/Views/Factura/Detalle.cshtml
@model Comercializadora.Models.Factura
@{
    ViewData["Title"] = "Detalle de Factura";
}

<h2>Factura #@Model.Id</h2>
<p><strong>Cliente:</strong> @Model.NombreCliente</p>
<p><strong>Fecha:</strong> @Model.Fecha.ToString("dd/MM/yyyy")</p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio Unitario</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
            foreach (var detalle in ViewBag.Detalles)
            {
                <tr>
                    <td>@i</td>
                    <td>@detalle.NombreProducto</td>
                    <td>@detalle.Cantidad</td>
                    <td>@detalle.PrecioUnitario</td>
                    <td>@(detalle.Cantidad* detalle.PrecioUnitario)</td>
                </tr>
                i++;
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4"><strong>Subtotal:</strong></td>
            <td>@Model.Subtotal</td>
        </tr>
        <tr>
            <td colspan="4"><strong>Impuesto (13%):</strong></td>
            <td>@Model.Impuesto</td>
        </tr>
        <tr>
            <td colspan="4"><strong>Total:</strong></td>
            <td>@Model.Total</td>
        </tr>
    </tfoot>
</table>

<a asp-action="Index" class="btn btn-secondary">Volver</a>

Comercializadora/Comercializadora/Views/Factura/Index.cshtml
@model List<Comercializadora.Models.Factura>

@{
    ViewData["Title"] = "Listado de Facturas";
}

<h2 class="mb-3">Gestión de Facturas</h2>

<a asp-action="Crear" class="btn btn-success mb-3">
    <i class="bi bi-plus-circle"></i> Crear Nueva Factura
</a>

<table class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>Nombre Cliente</th>
            <th>Fecha</th>
            <th>Subtotal</th>
            <th>Impuesto</th>
            <th>Total</th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var factura in Model)
        {
            <tr>
                <td>@factura.Id</td>
                <td>@factura.NombreCliente</td>
                <td>@factura.Fecha</td>
                <td>@factura.Subtotal</td>
                <td>@factura.Impuesto</td>
                <td class="fw-bold">@factura.Total</td>
                <td class="text-center">
                    <a asp-controller="DetalleFactura"
                       asp-action="Crear"
                       asp-route-id="@factura.Id"
                       class="btn btn-primary btn-sm">
                         Agregar Producto
                    </a>
                    <a asp-controller="Factura"
                       asp-action="Detalle"
                       asp-route-id="@factura.Id"
                       class="btn btn-info btn-sm">
                        Ver Detalle
                    </a>
                    <a asp-controller="Factura"
                       asp-action="DescargarTxt"
                       asp-route-id="@factura.Id"
                       class="btn btn-success btn-sm">
                        Descargar TXT
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Comercializadora/Comercializadora/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Comercializadora/Comercializadora/Views/Producto/Crear.cshtml
@model Comercializadora.Models.Producto

@{
    ViewData["Title"] = "Crear Producto";
}

<h2 class="mb-3">Crear Producto</h2>

<form asp-action="Crear"
      method="post"
      enctype="multipart/form-data"
      class="row g-3">

    <div class="col-md-6">
        <label asp-for="Nombre" class="form-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="col-md-6">
        <label asp-for="Precio" class="form-label"></label>
        <input asp-for="Precio" class="form-control" />
        <span asp-validation-for="Precio" class="text-danger"></span>
    </div>


    <div class="col-12">
        <button type="submit" class="btn btn-primary">
            Guardar
        </button>
        <a asp-action="Index" class="btn btn-secondary">
            Cancelar
        </a>
    </div>
</form>

Comercializadora/Comercializadora/Views/Producto/Index.cshtml
@model List<Comercializadora.Models.Producto>

@{
    ViewData["Title"] = "Producto";
}

<h2 class="mb-3"> Producto</h2>

<a asp-action="Crear" class="btn btn-success mb-3">
    Crear producto
</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var producto in Model)
        {
            <tr>
                <td>@producto.Id</td>
                <td>@producto.Nombre</td>
                <td>@producto.Precio</td>

            </tr>
        }
    </tbody>
</table>

Comercializadora/Comercializadora/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comercializadora</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Comercializadora.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comercializadora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Comercializadora - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>